# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import clientes_pb2 as clientes__pb2


class ClientesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuscaCliente = channel.unary_unary(
                '/clientes.Clientes/BuscaCliente',
                request_serializer=clientes__pb2.ClientesRequest.SerializeToString,
                response_deserializer=clientes__pb2.ClienteResponse.FromString,
                )
        self.TodosClientes = channel.unary_unary(
                '/clientes.Clientes/TodosClientes',
                request_serializer=clientes__pb2.Empty.SerializeToString,
                response_deserializer=clientes__pb2.ClientesList.FromString,
                )


class ClientesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuscaCliente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TodosClientes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuscaCliente': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscaCliente,
                    request_deserializer=clientes__pb2.ClientesRequest.FromString,
                    response_serializer=clientes__pb2.ClienteResponse.SerializeToString,
            ),
            'TodosClientes': grpc.unary_unary_rpc_method_handler(
                    servicer.TodosClientes,
                    request_deserializer=clientes__pb2.Empty.FromString,
                    response_serializer=clientes__pb2.ClientesList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'clientes.Clientes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Clientes(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuscaCliente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientes.Clientes/BuscaCliente',
            clientes__pb2.ClientesRequest.SerializeToString,
            clientes__pb2.ClienteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TodosClientes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/clientes.Clientes/TodosClientes',
            clientes__pb2.Empty.SerializeToString,
            clientes__pb2.ClientesList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
